# Generated by Django 5.2 on 2025-05-25 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_role_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.JSONField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='presentaciones/')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='colabora_en', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VersionPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.JSONField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='api.presentacion')),
            ],
        ),
    ]
